################################################################################
# Style file for markdownlint.
#
# https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md
#
# This file is referenced by the project `.mdlrc`.
################################################################################

#===============================================================================
# Start with all built-in rules.
# https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
all

#===============================================================================
# Override default parameters for some built-in rules.
# https://github.com/markdownlint/markdownlint/blob/master/docs/creating_styles.md#parameters

exclude_tag :line_length
# Do not allow multiple consecutive blank lines.
rule 'MD012'

#===============================================================================
# Exclude the rules I disagree with.

# IMHO it's easier to read lists like:
# * outmost indent
#   - one indent
#   - second indent
# * Another major bullet
exclude_rule 'MD004' # Unordered list style
exclude_rule 'MD005' # Unordered list indentation style
exclude_rule 'MD007'

exclude_rule 'MD013' # Allow long lines for autogenerated docs

# Ordered lists are fine.
exclude_rule 'MD029'

# The first line doesn't always need to be a top level header.
exclude_rule 'MD041'

# I find it necessary to use '<br/>' to force line breaks.
exclude_rule 'MD033' # Inline HTML

# Using bare URLs is fine.
exclude_rule 'MD034'

# Exclude rules reverted by markdownlint
# (https://github.com/markdownlint/markdownlint/commit/f97a364ed880a690f509d144641b89ba16dd92e5)
exclude_rule 'MD055'
exclude_rule 'MD056'
exclude_rule 'MD057'
