---
name: dotfile tests
on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com

jobs:
  bats_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: recursive

      - name: Set up git config
        run: |
          git config --global user.email "${{ github.event.inputs.git_email }}"
          git config --global user.name "${{ github.event.inputs.git_user }}"

      - name: Install dependencies
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
              sudo apt-get update
              sudo apt-get install -y curl git zsh python3-venv
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
              brew install curl git zsh
          fi

      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install ansible
          ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main

      - name: Install the dotfiles
        run: |
          source venv/bin/activate
          chmod +x install_dot_files.sh
          if ./install_dot_files.sh; then
            echo "Dotfiles installed successfully"
          else
            echo "Dotfiles installation failed"
            exit 1
          fi

      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
        with:
          bats-version: 1.2.1

      - name: Run Bats tests
        run: |
          source venv/bin/activate
          bats tests/test-go.bats

  dotfile_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: recursive

      - name: Set up git config
        run: |
          git config --global user.email "${{ github.event.inputs.git_email }}"
          git config --global user.name "${{ github.event.inputs.git_user }}"

      - name: Install asdf cli
        uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2

      - name: Install dependencies
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
              sudo apt-get update
              sudo apt-get install -y curl git zsh python3-venv
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
              brew install curl git zsh
          fi

      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install ansible
          ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main

      - name: Install the dotfiles
        run: |
          source venv/bin/activate
          chmod +x install_dot_files.sh
          if ./install_dot_files.sh; then
            echo "Dotfiles installed successfully"
          else
            echo "Dotfiles installation failed"
            exit 1
          fi

      - name: Confirm dotfiles are installed and working
        run: |
          source venv/bin/activate
          source ~/.zshrc
          cat ~/.zshrc
          source ~/.dotfiles/python
          ls -lart ~/.dotfiles
          which ipaddr
          which go
          which run_playbook
        shell: zsh {0}
