---
name: dotfile tests
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com

jobs:
  # setup:
  #   name: Install and test my personal dotfiles
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  # steps:
  #   - name: Set up git repository
  #     uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
  #     with:
  #       submodules: recursive

  # - name: Install asdf cli
  #   uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2

  # - name: Set up Python
  #   uses: actions/setup-python@v4

  # - name: Install dependencies
  #   run: |
  #     if [[ "${RUNNER_OS}" == "Linux" ]]; then
  #         sudo apt-get update
  #         sudo apt-get install -y curl git zsh
  #     fi
  #     python3 -m pip install ansible
  #     ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main

  # - name: Install the dotfiles
  #   run: |
  #     chmod +x install_dot_files.sh
  #     if ./install_dot_files.sh; then
  #       echo "Dotfiles installed successfully"
  #     else
  #       echo "Dotfiles installation failed"
  #       exit 1
  #     fi

  bats_tests:
    # needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
              sudo apt-get update
              sudo apt-get install -y curl git zsh
          fi
          python3 -m pip install ansible
          ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main

      - name: Install the dotfiles
        run: |
          set -x # Enable verbose output
          chmod +x install_dot_files.sh
          if ./install_dot_files.sh; then
            echo "Dotfiles installed successfully"
          else
            echo "Dotfiles installation failed"
            exit 1
          fi

      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
        with:
          bats-version: 1.2.1

      - name: Set up temporary git config to satisfy tests
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Run Bats tests
        run: |
          bats tests/test-go.bats
          # bats tests/{test-go,test-bashutils}.bats # for when I have time to make things work in github actions

  dotfile_test:
    # needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: recursive

      - name: Install asdf cli
        uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2

      - name: Install dependencies
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
              sudo apt-get update
              sudo apt-get install -y curl git zsh
          fi
          python3 -m pip install ansible
          ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main

      - name: Install the dotfiles
        run: |
          chmod +x install_dot_files.sh
          if ./install_dot_files.sh; then
            echo "Dotfiles installed successfully"
          else
            echo "Dotfiles installation failed"
            exit 1
          fi

      - name: Confirm dotfiles are installed and working
        run: |
          source ~/.zshrc
          cat ~/.zshrc
          source ~/.dotfiles/python
          ls -lart ~/.dotfiles
          which ipaddr
          which go
          which run_playbook
        shell: zsh {0}

        # # For debugging:
        # - name: Setup tmate session
        #   uses: mxschmitt/action-tmate@v3
        #   if: ${{ failure() }}
        #   with:
        #     limit-access-to-actor: true
