---
name: dotfile tests
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  bats_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Clone git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive

      - name: Setup git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
              sudo apt-get update
              sudo apt-get install -y curl git zsh python3-venv
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
              brew install curl git zsh
          fi

      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install ansible
          ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main
          ln -s -f $(pwd)/venv/bin/python /usr/local/bin/python

      - name: Install the dotfiles
        run: |
          source venv/bin/activate
          chmod +x install_dot_files.sh
          if ./install_dot_files.sh; then
            echo "Dotfiles installed successfully"
          else
            echo "Dotfiles installation failed"
            exit 1
          fi

      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
        with:
          bats-version: 1.2.1

      - name: Run Bats tests
        run: |
          source venv/bin/activate
          bats tests/test-go.bats

  dotfile_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Clone git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive

      - name: Setup git config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.x"

      - name: Install asdf cli
        uses: asdf-vm/actions/setup@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2

      - name: Install dependencies
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
              sudo apt-get update
              sudo apt-get install -y curl git zsh python3-venv
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
              brew install curl git zsh
          fi

      - name: Set up Python virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install ansible
          ansible-galaxy collection install git+https://github.com/cowdogmoo/workstation.git,main
          ln -s -f $(pwd)/venv/bin/python /usr/local/bin/python

      - name: Install the dotfiles
        run: |
          source venv/bin/activate
          chmod +x install_dot_files.sh
          if ./install_dot_files.sh; then
            echo "Dotfiles installed successfully"
          else
            echo "Dotfiles installation failed"
            exit 1
          fi

      - name: Confirm dotfiles are installed and working
        run: |
          source venv/bin/activate
          source ~/.zshrc
          cat ~/.zshrc
          source ~/.dotfiles/python
          ls -lart ~/.dotfiles
          which ipaddr
          which go
          which run_playbook
        shell: zsh {0}
