---
name: Test dotfiles
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com

jobs:
  test_dotfile_install:
    name: Install and test my personal dotfiles
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3.3.0

      - name: "Set up Cloud SDK (dependency for gcloud dotfile)"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Install dependencies
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
               sudo apt-get update
               sudo apt-get install -y curl zsh
               # Fix permissions to avoid annoying message
               sudo chmod -R 755 /usr/share/zsh
               sudo chmod -R 755 /usr/share/zsh/vendor-completions
          # Resource: https://stackoverflow.com/questions/57946173/github-actions-run-step-on-specific-os
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            echo "Nothing to do here"
          else
               echo "${RUNNER_OS} not supported"
               exit 1
          fi

          # Get ohmyzsh
          bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

      - name: Run dotfiles installation script
        run: bash install_dot_files.sh

      - name: Confirm dotfiles are installed and working
        run: |
          ls -lart ~/.dotfiles
          source ~/.zshrc
          ipaddr
          source ~/.gvm/scripts/gvm
          go version
          cat ~/.cobra.yaml
        shell: zsh {0}
